console.log("My first console project");
var first_name="Dona";
var second_name="jose";
var full_name=first_name.concat(second_name);
var a=10;
var b=15;
var add= a+b;
console.log(add);
var sub= a-b;
console.log(sub);
var mul=a*b;
console.log(mul);
var div=a/b;
console.log(div);
